#: kivy 1.0

<Controller>:
    BoxLayout:
        orientation: 'vertical'

        BoxLayout:
            orientation: 'horizontal'
            padding: 20

            Button:
                text: 'b0'
            Button:
                text: 'br1'
            Button:
                text: 'br2'
            Button:
                text: 'b3'
            Button:
                text: 'b4'
            Button:
                text: 'b5'

        FloatLayout:

